export const INIT_FIGHTERZ = 'INIT_FIGHTERZ';
export const GET_FIGHTERZ_BY_ID = 'GET_FIGHTERZ_BY_ID';
export const ADD_FIGHTERZ = 'ADD_FIGHTERZ';
export const REMOVE_FIGHTERZ = 'REMOVE_FIGHTERZ';
export const EDIT_FIGHTERZ = 'EDIT_FIGHTERZ';
export const FETCH_FIGHTERZ_FAILED = 'FETCH_FIGHTERZS_FAILED';